### PR TITLE
fix the API usage in the readme.

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey, I don't quite get this. I do you think this is necessary? I include it like this:

```js
import { ready } from '../node_modules/readyjs/dist/ready.js'

// This allows for:
ready(…
```

**Comment by stof** [comment]
but this is not what the readme was saying either. The readme was mentioning `readyjs`, and the only place where I found this name is in the IIFE build, which defines a `readyjs` global variable with a `ready` method attached on it.

Documenting both the usage with IIFE and the usage as import would actually be even better.

**Comment by lukasoppermann** [comment]
Great idea @stof, do you want to adjust this PR to include both the `import` and the `IIFE` version?
Probably the `import { ready } from '../node_modules/readyjs/dist/ready.js'` part should be in the `import` example.

**Comment by lukasoppermann** [comment]
Fixed it now.

**Pull request closed without merging**
